---
title: "final"
author: "Srini Chelimilla"
date: "2022-12-03"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plotly)
library(htmltools)
library(devtools)
library(caret)
library(NbClust)
library(data.table)
library(dplyr)
library(ROCR)
library(rpart.plot)
library(MLmetrics)
```


```{r}
getwd()
#setwd("./finalProjectMarkdown/Levels_Fyi_Salary_Data.csv")

# Read file
salaries = read.csv('Levels_Fyi_Salary_Data.csv')
View(salaries)
```

```{r}
# Get rid of NAs
dim(salaries)
salaries = salaries[complete.cases(salaries), ]
dim(salaries)

# before: 62642 rows
# after: 21575 rows
```

```{r}
# Look at variable types
str(salaries)

#this gets all the column value in companies except for those
salaries2 = salaries %>% filter(!company %in% c("Amazon", "Facebook", "Google", "Microsoft"))

# convert to factors
salaries[,c(2, 3, 4, 6, 13, 18, 19, 20, 21, 22, 28, 29)] <- lapply(salaries[,c(2, 3, 4, 6, 13, 18, 19, 20, 21, 22, 28, 29)], as.factor)
 
# get rid of columns
#salaries <- salaries[, c(-1, -9, -10, -11, -12, -14, -15, -16, -17, -23, -24, -25, -26, -27)]
salaries <- salaries[,-c(1,9,14)]



#str(salaries)
```

```{r}
table(salaries$tag)
```


```{r}
# collapse factor variables

vec = pull(salaries2, company)
View(vec)

salaries$company <- fct_collapse(salaries$company, 
                           amazon = "Amazon",
                           facebook = "Facebook",
                           google = "Google",
                           microsoft = "Microsoft",
                           other= vec
                          )
```


```{r}
table(salaries$company)
```


### not sure if we need to normalize
```{r}
# Normalize data
normalize = function(x){
 (x - min(x)) / (max(x) - min(x))
}

numerics = names(select_if(salaries, is.numeric))
salaries[numerics] = lapply(salaries[numerics], normalize)
```

```{r}
# splitting data
set.seed(1999)
part_index_1 <- caret::createDataPartition(salaries$totalyearlycompensation,
                                           times=1,
                                           p = 0.7,
                                           groups=1,
                                           list=FALSE)

train <- salaries[part_index_1, ]
tune_and_test <- salaries[-part_index_1, ]
train
dim(train)

tune_and_test_index <- createDataPartition(tune_and_test$totalyearlycompensation,
                                           p = .5,
                                           list = FALSE,
                                           times = 1)

tune <- tune_and_test[tune_and_test_index, ]
test <- tune_and_test[-tune_and_test_index, ]


dim(train)
dim(test) 
dim(tune)

```

# Base model
```{r}
#Build the model using the training data, rpart2, and repeated cross validation

features <- train[,-4] #dropping column 4 (totalyearlycompensation) because it's the target variable

target <- train$totalyearlycompensation


#Cross validation process
fitControl <- trainControl(method = "repeatedcv",
                          number = 10,
                          repeats = 5) 

#Setting a hyper-parameter search
tree.grid <- expand.grid(maxdepth=c(3:20))


#Train the models
set.seed(1984)

salaries_model <- train(x=features,
                y=target,
                method="rpart2",
                trControl=fitControl,
                tuneGrid=tree.grid,
                metric="RMSE")
```

```{r}
# model performance

salaries_model
# RMSE = 21.29
# Rsquared = 0.039

plot(salaries_model)
# model does not change with varying tree depth

varImp(salaries_model)
# Most important variables are instrumentalness, loudness, acousticness, audio valence, and danceability
```

```{r}
# predicting using base model and test set
tree.grid <- expand.grid(maxdepth=c(3:20))

salaries_model <- train(x=features,
                y=target,
                method="rpart2",
                trControl=fitControl,
                tuneGrid=tree.grid,
                metric="RMSE")

pred_test_reg <- predict(salaries_model,test)

head(salaries_model)

postResample(pred = pred_test_reg,obs = test$totalyearlycompensation)

comparison <- test['totalyearlycompensation']
comparison <- rbind(comparison, data.frame(predicted = pred_test_reg))

comparison2 <- data.frame(test['totalyearlycompensation'], pred_test_reg)
```

